INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('3D-udskrivning','https://en.wikipedia.org/wiki/3D_printing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Akrobatik','https://en.wikipedia.org/wiki/Acrobatics','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skuespil','https://en.wikipedia.org/wiki/Acting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Amatørradio','https://en.wikipedia.org/wiki/Amateur_radio','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Animation','https://en.wikipedia.org/wiki/Animation','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Aquascaping','https://en.wikipedia.org/wiki/Aquascaping','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Astrologi','https://en.wikipedia.org/wiki/Astrology','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bagning','https://en.wikipedia.org/wiki/Baking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Baton snurrer','https://en.wikipedia.org/wiki/Baton_twirling','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Blogging','https://en.wikipedia.org/wiki/Blogging','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Brætspil','https://en.wikipedia.org/wiki/Board_game','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bogdiskussionsklub','https://en.wikipedia.org/wiki/Book_discussion_club','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gendannelse af bøger','https://en.wikipedia.org/wiki/Book_restoration','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bowling','https://en.wikipedia.org/wiki/Bowling','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Brasiliansk jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Brødfremstilling','https://en.wikipedia.org/wiki/Breadmaking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bygning','https://en.wikipedia.org/wiki/Building','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cabaret','https://en.wikipedia.org/wiki/Cabaret','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kalligrafi','https://en.wikipedia.org/wiki/Calligraphy','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Lysfremstilling','https://en.wikipedia.org/wiki/Candle_making','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Slikfremstilling','https://en.wikipedia.org/wiki/Candy_making','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bil','https://en.wikipedia.org/wiki/Car','GENERAL','COMBO');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kortspil','https://en.wikipedia.org/wiki/Card_games','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cardistry','https://en.wikipedia.org/wiki/Cardistry','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ostemagning','https://en.wikipedia.org/wiki/Cheesemaking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rengøring','https://en.wikipedia.org/wiki/Cleaning','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tøj','https://en.wikipedia.org/wiki/Clothing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hjemmelavet kaffe','https://en.wikipedia.org/wiki/Home_roasting_coffee','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Indsamling','https://en.wikipedia.org/wiki/Collecting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Malebog','https://en.wikipedia.org/wiki/Coloring_book','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Computer programmering','https://en.wikipedia.org/wiki/Computer_programming','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Konfekture','https://en.wikipedia.org/wiki/Confectionery','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Madlavning','https://en.wikipedia.org/wiki/Cooking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cosplaying','https://en.wikipedia.org/wiki/Cosplaying','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kuponering','https://en.wikipedia.org/wiki/Couponing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Håndværk','https://en.wikipedia.org/wiki/Craft','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kreativ skrivning','https://en.wikipedia.org/wiki/Creative_writing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hækling','https://en.wikipedia.org/wiki/Crocheting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Korssting','https://en.wikipedia.org/wiki/Cross-stitch','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Krydsogtværs','https://en.wikipedia.org/wiki/Crossword_puzzles','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kryptografi','https://en.wikipedia.org/wiki/Cryptography','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cue sport','https://en.wikipedia.org/wiki/Cue_sports','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dans','https://en.wikipedia.org/wiki/Dance','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Digital kunst','https://en.wikipedia.org/wiki/Digital_art','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Distro-hopping','https://en.wikipedia.org/wiki/Distro-hopping','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Disc-jockey','https://en.wikipedia.org/wiki/Disc-jockey','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gør det selv','https://en.wikipedia.org/wiki/Do_it_yourself','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Drama','https://en.wikipedia.org/wiki/Drama','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tegning','https://en.wikipedia.org/wiki/Drawing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Blandet drik','https://en.wikipedia.org/wiki/Mixed_drink','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Drikker','https://en.wikipedia.org/wiki/Drinking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Elektroniske spil','https://en.wikipedia.org/wiki/Electronic_games','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Elektronik','https://en.wikipedia.org/wiki/Electronics','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Broderi','https://en.wikipedia.org/wiki/Embroidery','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Eksperimenterer','https://en.wikipedia.org/wiki/Experimenting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fantasy sport','https://en.wikipedia.org/wiki/Fantasy_sport','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mode','https://en.wikipedia.org/wiki/Fashion','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mode design','https://en.wikipedia.org/wiki/Fashion_design','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fiskearbejde','https://en.wikipedia.org/wiki/Fishkeeping','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Filmfremstilling','https://en.wikipedia.org/wiki/Filmmaking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Blomsterbinding','https://en.wikipedia.org/wiki/Flower_arranging','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fluebinding','https://en.wikipedia.org/wiki/Fly_tying','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Andet sprog erhvervelse','https://en.wikipedia.org/wiki/Second-language_acquisition','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Møbel','https://en.wikipedia.org/wiki/Furniture','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Spil','https://en.wikipedia.org/wiki/Games','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bordspil','https://en.wikipedia.org/wiki/Tabletop_game','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rollespil','https://en.wikipedia.org/wiki/Role-playing_game','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Slægtsforskning','https://en.wikipedia.org/wiki/Genealogy','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Honningkagehus','https://en.wikipedia.org/wiki/Gingerbread_house','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Glasblæsning','https://en.wikipedia.org/wiki/Glassblowing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Grafisk design','https://en.wikipedia.org/wiki/Graphic_design','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gunsmithing','https://en.wikipedia.org/wiki/Gunsmithing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gymnastik','https://en.wikipedia.org/wiki/Gymnastics','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hacker','https://en.wikipedia.org/wiki/Hacker','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Herpetokultur','https://en.wikipedia.org/wiki/Herpetoculture','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hjemmeforbedring','https://en.wikipedia.org/wiki/Home_improvement','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hjemmebrygning','https://en.wikipedia.org/wiki/Homebrewing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Pleje af husplanter','https://en.wikipedia.org/wiki/Houseplant_care','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hula bøjning','https://en.wikipedia.org/wiki/Hula_hooping','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Humor','https://en.wikipedia.org/wiki/Humor','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hydroponics','https://en.wikipedia.org/wiki/Hydroponics','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skøjteløb','https://en.wikipedia.org/wiki/Ice_skating','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Smykkefremstilling','https://en.wikipedia.org/wiki/Jewelry_making','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Puslespil','https://en.wikipedia.org/wiki/Jigsaw_puzzles','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dagbog','https://en.wikipedia.org/wiki/Diary','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Jonglere','https://en.wikipedia.org/wiki/Juggling','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Karaoke','https://en.wikipedia.org/wiki/Karaoke','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Karate','https://en.wikipedia.org/wiki/Karate','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kendama','https://en.wikipedia.org/wiki/Kendama','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Knivfremstilling','https://en.wikipedia.org/wiki/Knife_making','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Strikning','https://en.wikipedia.org/wiki/Knitting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Knude binder','https://en.wikipedia.org/wiki/Knot_tying','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kombucha','https://en.wikipedia.org/wiki/Kombucha','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Blonder','https://en.wikipedia.org/wiki/Lace_making','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Lapidary','https://en.wikipedia.org/wiki/Lapidary','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Læder håndværk','https://en.wikipedia.org/wiki/Leather_crafting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Lego','https://en.wikipedia.org/wiki/Lego','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('musik','https://en.wikipedia.org/wiki/Music','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Podcasts','https://en.wikipedia.org/wiki/Podcasts','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Låseplukning','https://en.wikipedia.org/wiki/Lock_picking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bearbejdning','https://en.wikipedia.org/wiki/Machining','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Macrame','https://en.wikipedia.org/wiki/Macrame','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Magi (illusion)','https://en.wikipedia.org/wiki/Magic_(illusion)','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Makeup','https://en.wikipedia.org/wiki/Makeup','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Labyrint','https://en.wikipedia.org/wiki/Maze','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Metalbearbejdning','https://en.wikipedia.org/wiki/Metalworking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Modelbygning','https://en.wikipedia.org/wiki/Model_building','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Model engineering','https://en.wikipedia.org/wiki/Model_engineering','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Negle kunst','https://en.wikipedia.org/wiki/Nail_art','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Nålepunkt','https://en.wikipedia.org/wiki/Needlepoint','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Origami','https://en.wikipedia.org/wiki/Origami','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Maleri','https://en.wikipedia.org/wiki/Painting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Håndflade','https://en.wikipedia.org/wiki/Palmistry','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Adoption af kæledyr','https://en.wikipedia.org/wiki/Pet_adoption','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Filateli','https://en.wikipedia.org/wiki/Philately','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fotografering','https://en.wikipedia.org/wiki/Photography','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Pilates','https://en.wikipedia.org/wiki/Pilates','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Poi (performance)','https://en.wikipedia.org/wiki/Poi_(performance_art)','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Pole Dancing (siden findes ikke)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Keramik','https://en.wikipedia.org/wiki/Pottery','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kraftløftning','https://en.wikipedia.org/wiki/Powerlifting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Praktiske vittigheder','https://en.wikipedia.org/wiki/Practical_jokes','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Presset blomsterhåndværk','https://en.wikipedia.org/wiki/Pressed_flower_craft','GENERAL','COLLECTING');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gåde','https://en.wikipedia.org/wiki/Puzzle','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Quilling','https://en.wikipedia.org/wiki/Quilling','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Quiltning','https://en.wikipedia.org/wiki/Quilting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Quizzer','https://en.wikipedia.org/wiki/Quizzes','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Radiostyret model','https://en.wikipedia.org/wiki/Radio-controlled_model','GENERAL','COLLECTING');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Modellering af jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport_modeling','GENERAL','COLLECTING');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rapping','https://en.wikipedia.org/wiki/Rapping','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Læsning','https://en.wikipedia.org/wiki/Reading','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Efterbehandling','https://en.wikipedia.org/wiki/Refinishing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Reiki','https://en.wikipedia.org/wiki/Reiki','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Robotkamp','https://en.wikipedia.org/wiki/Robot_combat','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rubiks terning','https://en.wikipedia.org/wiki/Rubik%27s_Cube','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Scrapbooking','https://en.wikipedia.org/wiki/Scrapbooking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('SCUBA Dykning','https://en.wikipedia.org/wiki/SCUBA_Diving','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Modellering','https://en.wikipedia.org/wiki/Sculpting','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Syning','https://en.wikipedia.org/wiki/Sewing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skomageri','https://en.wikipedia.org/wiki/Shoemaking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Synger','https://en.wikipedia.org/wiki/Singing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skitse (tegning)','https://en.wikipedia.org/wiki/Sketch_(drawing)','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sjippetov','https://en.wikipedia.org/wiki/Skipping_rope','GENERAL','COMBO');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Slot bil','https://en.wikipedia.org/wiki/Slot_car','GENERAL','COLLECTING');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sæbefremstilling','https://en.wikipedia.org/wiki/Soapmaking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sociale medier','https://en.wikipedia.org/wiki/Social_media','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Regneark','https://en.wikipedia.org/wiki/Spreadsheets','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Stand-up','https://en.wikipedia.org/wiki/Stand-up_comedy','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Frimærkesamling','https://en.wikipedia.org/wiki/Stamp_collecting','GENERAL','COLLECTING');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bordtennis','https://en.wikipedia.org/wiki/Table_tennis','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tarot','https://en.wikipedia.org/wiki/Tarot','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Taksidermi','https://en.wikipedia.org/wiki/Taxidermy','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Velgørenhedsbutik','https://en.wikipedia.org/wiki/Charity_shop','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Videoredigering','https://en.wikipedia.org/wiki/Video_editing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Udvikling af videospil','https://en.wikipedia.org/wiki/Video_game_development','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Videospil','https://en.wikipedia.org/wiki/Video_gaming','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Videografi','https://en.wikipedia.org/wiki/Videography','GENERAL','COMBO');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Virtual reality','https://en.wikipedia.org/wiki/Virtual_reality','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Film','https://en.wikipedia.org/wiki/Movies','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tv-program','https://en.wikipedia.org/wiki/Television_program','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Voksning','https://en.wikipedia.org/wiki/Waxing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vævning','https://en.wikipedia.org/wiki/Weaving','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Webtoon','https://en.wikipedia.org/wiki/Webtoon','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vægt træning','https://en.wikipedia.org/wiki/Weight_training','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Svejsning','https://en.wikipedia.org/wiki/Welding','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hviskende','https://en.wikipedia.org/wiki/Whittling','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vinfremstilling','https://en.wikipedia.org/wiki/Winemaking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Træskæring','https://en.wikipedia.org/wiki/Wood_carving','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Træbearbejdning','https://en.wikipedia.org/wiki/Woodworking','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ordsøgninger','https://en.wikipedia.org/wiki/Word_searches','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Verdensbygning','https://en.wikipedia.org/wiki/Worldbuilding','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skrivning','https://en.wikipedia.org/wiki/Writing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Yo-yoing','https://en.wikipedia.org/wiki/Yo-yoing','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Yoga','https://en.wikipedia.org/wiki/Yoga','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Zumba','https://en.wikipedia.org/wiki/Zumba','GENERAL','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Luftsport','https://en.wikipedia.org/wiki/Air_sports','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Airsoft','https://en.wikipedia.org/wiki/Airsoft','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Amatørgeologi','https://en.wikipedia.org/wiki/Amateur_geology','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Forlystelsespark','https://en.wikipedia.org/wiki/Amusement_park','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bueskydning','https://en.wikipedia.org/wiki/Archery','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Astronomi','https://en.wikipedia.org/wiki/Astronomy','GENERAL','EDUCATIONAL');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Backpacking (vildmark)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Badminton','https://en.wikipedia.org/wiki/Badminton','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Base jumping','https://en.wikipedia.org/wiki/BASE_jumping','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Baseball','https://en.wikipedia.org/wiki/Baseball','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Basketball','https://en.wikipedia.org/wiki/Basketball','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Biavl','https://en.wikipedia.org/wiki/Beekeeping','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fuglekiggeri','https://en.wikipedia.org/wiki/Birdwatching','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Smedarbejde','https://en.wikipedia.org/wiki/Blacksmithing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('BMX','https://en.wikipedia.org/wiki/BMX','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Brætsport','https://en.wikipedia.org/wiki/Board_sports','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bodybuilding','https://en.wikipedia.org/wiki/Bodybuilding','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bonsai','https://en.wikipedia.org/wiki/Bonsai','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sommerfugletur','https://en.wikipedia.org/wiki/Butterfly_watching','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bus','https://en.wikipedia.org/wiki/Bus','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Camping','https://en.wikipedia.org/wiki/Camping','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kanosejlads','https://en.wikipedia.org/wiki/Canoeing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Canyoning','https://en.wikipedia.org/wiki/Canyoning','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Huleforskning','https://en.wikipedia.org/wiki/Caving','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kompostering','https://en.wikipedia.org/wiki/Composting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cykling','https://en.wikipedia.org/wiki/Cycling','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dowsing','https://en.wikipedia.org/wiki/Dowsing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kørsel','https://en.wikipedia.org/wiki/Driving','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Landbrug','https://en.wikipedia.org/wiki/Farming','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fiskeri','https://en.wikipedia.org/wiki/Fishing','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Flag fodbold','https://en.wikipedia.org/wiki/Flag_football','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Blomst','https://en.wikipedia.org/wiki/Flower','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Luftfart','https://en.wikipedia.org/wiki/Aviation','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Flyvende skive','https://en.wikipedia.org/wiki/Flying_disc','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Foder','https://en.wikipedia.org/wiki/Foraging','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fossicking','https://en.wikipedia.org/wiki/Fossicking','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Freestyle fodbold','https://en.wikipedia.org/wiki/Freestyle_football','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Havearbejde','https://en.wikipedia.org/wiki/Gardening','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Geocaching','https://en.wikipedia.org/wiki/Geocaching','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Spøgelsesjagt','https://en.wikipedia.org/wiki/Ghost_hunting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Guldprospektering','https://en.wikipedia.org/wiki/Gold_prospecting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Graffiti','https://en.wikipedia.org/wiki/Graffiti','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Håndbold','https://en.wikipedia.org/wiki/Handball','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Naturlægemidler','https://en.wikipedia.org/wiki/Herbalism','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Herping','https://en.wikipedia.org/wiki/Herping','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Højeffektiv raket','https://en.wikipedia.org/wiki/High-power_rocketry','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vandreture','https://en.wikipedia.org/wiki/Hiking','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('hobby hest','https://en.wikipedia.org/wiki/hobby_horse','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('hobby tunneling','https://en.wikipedia.org/wiki/hobby_tunneling','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hooping','https://en.wikipedia.org/wiki/Hooping','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ridning','https://en.wikipedia.org/wiki/Horseback_riding','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Jagt','https://en.wikipedia.org/wiki/Hunting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('In-line skating','https://en.wikipedia.org/wiki/Inline_skating','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Løbe','https://en.wikipedia.org/wiki/Jogging','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ro kajak','https://en.wikipedia.org/wiki/Kayaking','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Glente','https://en.wikipedia.org/wiki/Kite','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kitesurfing','https://en.wikipedia.org/wiki/Kitesurfing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Lacrosse','https://en.wikipedia.org/wiki/Lacrosse','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('LARPing','https://en.wikipedia.org/wiki/LARPing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Letterboxing (hobby)','https://en.wikipedia.org/wiki/Letterboxing_(hobby)','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Longboarding','https://en.wikipedia.org/wiki/Longboarding','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kampsport','https://en.wikipedia.org/wiki/Martial_arts','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Metaldetektor','https://en.wikipedia.org/wiki/Metal_detector','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Meteorologi','https://en.wikipedia.org/wiki/Meteorology','GENERAL','OBSERVATION');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Motorsport','https://en.wikipedia.org/wiki/Motor_sports','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mountainbiking','https://en.wikipedia.org/wiki/Mountain_biking','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bjergbestigning','https://en.wikipedia.org/wiki/Mountaineering','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Museum','https://en.wikipedia.org/wiki/Museum','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Svampejagt','https://en.wikipedia.org/wiki/Mushroom_hunting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mykologi','https://en.wikipedia.org/wiki/Mycology','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Netball','https://en.wikipedia.org/wiki/Netball','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Nordisk skøjteløb','https://en.wikipedia.org/wiki/Nordic_skating','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Orientering','https://en.wikipedia.org/wiki/Orienteering','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Paintball','https://en.wikipedia.org/wiki/Paintball','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Parkour','https://en.wikipedia.org/wiki/Parkour','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Podcast','https://en.wikipedia.org/wiki/Podcast','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Polo','https://en.wikipedia.org/wiki/Polo','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Offentlig transport','https://en.wikipedia.org/wiki/Public_transport','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rafting','https://en.wikipedia.org/wiki/Rafting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Jernbane','https://en.wikipedia.org/wiki/Railway','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rappellering','https://en.wikipedia.org/wiki/Rappelling','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Road Cykling','https://en.wikipedia.org/wiki/Road_Cycling','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rulleskøjteløb','https://en.wikipedia.org/wiki/Roller_skating','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rugby fodbold','https://en.wikipedia.org/wiki/Rugby_football','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Løb','https://en.wikipedia.org/wiki/Running','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sejler','https://en.wikipedia.org/wiki/Sailing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sand kunst og leg','https://en.wikipedia.org/wiki/Sand_art_and_play','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Spejder','https://en.wikipedia.org/wiki/Scouting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dykning','https://en.wikipedia.org/wiki/Scuba_diving','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sculling','https://en.wikipedia.org/wiki/Sculling','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Roning (sport)','https://en.wikipedia.org/wiki/Rowing_(sport)','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Optagelse','https://en.wikipedia.org/wiki/Shooting','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Handle ind','https://en.wikipedia.org/wiki/Shopping','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Shuffleboard','https://en.wikipedia.org/wiki/Shuffleboard','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skateboarding','https://en.wikipedia.org/wiki/Skateboarding','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Stå på ski','https://en.wikipedia.org/wiki/Skiing','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skimboarding','https://en.wikipedia.org/wiki/Skimboarding','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Faldskærmsudspring','https://en.wikipedia.org/wiki/Skydiving','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Slacklining','https://en.wikipedia.org/wiki/Slacklining','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Snowboarding','https://en.wikipedia.org/wiki/Snowboarding','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Snescooterkørsel','https://en.wikipedia.org/wiki/Snowmobiling','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Snesko','https://en.wikipedia.org/wiki/Snowshoeing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fodbold','https://en.wikipedia.org/wiki/Soccer','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sten springer over','https://en.wikipedia.org/wiki/Stone_skipping','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Solbadning','https://en.wikipedia.org/wiki/Sun_bathing','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Surfing','https://en.wikipedia.org/wiki/Surfing','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Overlevelse','https://en.wikipedia.org/wiki/Survivalism','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Menneskelig svømning','https://en.wikipedia.org/wiki/Human_swimming','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Taekwondo','https://en.wikipedia.org/wiki/Taekwondo','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tai Chi','https://en.wikipedia.org/wiki/Tai_chi','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tennis','https://en.wikipedia.org/wiki/Tennis','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Topiary','https://en.wikipedia.org/wiki/Topiary','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Turisme','https://en.wikipedia.org/wiki/Tourism','GENERAL','CONCERT');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gennem vandring','https://en.wikipedia.org/wiki/Thru-hiking','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Messe','https://en.wikipedia.org/wiki/Trade_fair','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rejse','https://en.wikipedia.org/wiki/Travel','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Byudforskning','https://en.wikipedia.org/wiki/Urban_exploration','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ferie','https://en.wikipedia.org/wiki/Vacation','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vegetabilsk landbrug','https://en.wikipedia.org/wiki/Vegetable_farming','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Restaurering af køretøjet','https://en.wikipedia.org/wiki/Vehicle_restoration','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gå','https://en.wikipedia.org/wiki/Walking','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vandsport','https://en.wikipedia.org/wiki/Water_sports','GENERAL','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Biologi','https://en.wikipedia.org/wiki/Biology','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kemi','https://en.wikipedia.org/wiki/Chemistry','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Elektrokemi','https://en.wikipedia.org/wiki/Electrochemistry','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Geografi','https://en.wikipedia.org/wiki/Geography','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Historie','https://en.wikipedia.org/wiki/History','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Matematik','https://en.wikipedia.org/wiki/Mathematics','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Psykologi','https://en.wikipedia.org/wiki/Psychology','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fysik','https://en.wikipedia.org/wiki/Physics','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Jernbanetransport','https://en.wikipedia.org/wiki/Rail_transport','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Videnskab og teknologi studier','https://en.wikipedia.org/wiki/Science_and_technology_studies','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sociale Studier','https://en.wikipedia.org/wiki/Social_studies','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sportsvidenskab','https://en.wikipedia.org/wiki/Sports_science','EDUCATIONAL','NA');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Action figur','https://en.wikipedia.org/wiki/Action_figure','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Antikviteter','https://en.wikipedia.org/wiki/Antiquing','COLLECTING','COMBO');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ant-holder','https://en.wikipedia.org/wiki/Ant-keeping','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kunstindsamling','https://en.wikipedia.org/wiki/Art_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bogindsamling','https://en.wikipedia.org/wiki/Book_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Knapopsamling','https://en.wikipedia.org/wiki/Button_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bytte kort','https://en.wikipedia.org/wiki/Trading_cards','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Møntindsamling','https://en.wikipedia.org/wiki/Coin_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tegneserieindsamling','https://en.wikipedia.org/wiki/Comic_book_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Deltiologi','https://en.wikipedia.org/wiki/Deltiology','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Die-cast legetøj','https://en.wikipedia.org/wiki/Die-cast_toy','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Digital hamstring','https://en.wikipedia.org/wiki/Digital_hoarding','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dukker','https://en.wikipedia.org/wiki/Dolls','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Elementindsamling','https://en.wikipedia.org/wiki/Element_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Flygtig','https://en.wikipedia.org/wiki/Ephemera','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Telefonkort','https://en.wikipedia.org/wiki/Telephone_card','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Knivopsamling','https://en.wikipedia.org/wiki/Knife_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Lotologi','https://en.wikipedia.org/wiki/Lotology','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Film memorabilia','https://en.wikipedia.org/wiki/Film_memorabilia','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fingeraftryk','https://en.wikipedia.org/wiki/Fingerprint','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Parfume','https://en.wikipedia.org/wiki/Perfume','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Phillumeny','https://en.wikipedia.org/wiki/Phillumeny','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Pladesamling','https://en.wikipedia.org/wiki/Record_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rock tumbling','https://en.wikipedia.org/wiki/Rock_tumbling','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Patch indsamling','https://en.wikipedia.org/wiki/Patch_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sko','https://en.wikipedia.org/wiki/Shoes','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sportsmemorabilia','https://en.wikipedia.org/wiki/Sports_memorabilia','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tøjdyr','https://en.wikipedia.org/wiki/Stuffed_toy','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Te pose','https://en.wikipedia.org/wiki/Tea_bag','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Billet (adgang)','https://en.wikipedia.org/wiki/Ticket_(admission)','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Legetøj','https://en.wikipedia.org/wiki/Toys','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Transitkort','https://en.wikipedia.org/wiki/Transit_map','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Samling af videospil','https://en.wikipedia.org/wiki/Video_game_collecting','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vintage biler','https://en.wikipedia.org/wiki/Vintage_cars','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vintage tøj','https://en.wikipedia.org/wiki/Vintage_clothing','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vinylplader','https://en.wikipedia.org/wiki/Vinyl_Records','COLLECTING','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Auto audiophilia','https://en.wikipedia.org/wiki/Auto_audiophilia','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fossil jagt','https://en.wikipedia.org/wiki/Fossil_hunting','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Insektindsamling','https://en.wikipedia.org/wiki/Insect_collecting','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Magnetfiskeri','https://en.wikipedia.org/wiki/Magnet_fishing','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Metaldetektering','https://en.wikipedia.org/wiki/Metal_detecting','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mineralindsamling','https://en.wikipedia.org/wiki/Mineral_collecting','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Stenbalancering','https://en.wikipedia.org/wiki/Rock_balancing','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Havglas','https://en.wikipedia.org/wiki/Sea_glass','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Muslingeskal','https://en.wikipedia.org/wiki/Seashell','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Stenopsamling','https://en.wikipedia.org/wiki/Stone_collecting','COLLECTING','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dyrepleje','https://en.wikipedia.org/wiki/Animal_fancy','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Øksekast','https://en.wikipedia.org/wiki/Axe_throwing','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Backgammon','https://en.wikipedia.org/wiki/Backgammon','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('SkønhedsKonkurrence','https://en.wikipedia.org/wiki/Beauty_pageant','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Boksning','https://en.wikipedia.org/wiki/Boxing','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kontraktsbro','https://en.wikipedia.org/wiki/Contract_Bridge','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kladder','https://en.wikipedia.org/wiki/Draughts','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cheerleading','https://en.wikipedia.org/wiki/Cheerleading','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skak','https://en.wikipedia.org/wiki/Chess','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Farvebeskyttelse (flag spinding)','https://en.wikipedia.org/wiki/Color_guard_(flag_spinning)','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cribbage','https://en.wikipedia.org/wiki/Cribbage','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Curling','https://en.wikipedia.org/wiki/Curling','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Konkurrencedygtig dans','https://en.wikipedia.org/wiki/Competitive_dance','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dart','https://en.wikipedia.org/wiki/Darts','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Debat','https://en.wikipedia.org/wiki/Debate','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Dominoer','https://en.wikipedia.org/wiki/Dominoes','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Konkurrencedygtig spisning','https://en.wikipedia.org/wiki/Competitive_eating','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Esports','https://en.wikipedia.org/wiki/Esports','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hegn','https://en.wikipedia.org/wiki/Fencing','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gå (spil)','https://en.wikipedia.org/wiki/Go_(game)','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ishockey','https://en.wikipedia.org/wiki/Ice_hockey','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Judo','https://en.wikipedia.org/wiki/Judo','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Jujitsu','https://en.wikipedia.org/wiki/Jujitsu','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kabaddi','https://en.wikipedia.org/wiki/Kabaddi','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ordspil','https://en.wikipedia.org/wiki/Word_games','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Lasermærke','https://en.wikipedia.org/wiki/Laser_tag','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mahjong','https://en.wikipedia.org/wiki/Mahjong','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kugler','https://en.wikipedia.org/wiki/Marbles','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Model FN','https://en.wikipedia.org/wiki/Model_United_Nations','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Poker','https://en.wikipedia.org/wiki/Poker','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Pool (cue sports)','https://en.wikipedia.org/wiki/Pool_(cue_sports)','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Shogi','https://en.wikipedia.org/wiki/Shogi','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Slot bilspil','https://en.wikipedia.org/wiki/Slot_car_racing','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hurtigkubning','https://en.wikipedia.org/wiki/Speedcubing','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Sport stabling','https://en.wikipedia.org/wiki/Sport_stacking','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bordfodbold','https://en.wikipedia.org/wiki/Table_football','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Volleyball','https://en.wikipedia.org/wiki/Volleyball','CONCERT','COMBO');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Brydning','https://en.wikipedia.org/wiki/Wrestling','CONCERT','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Association fodbold','https://en.wikipedia.org/wiki/Association_football','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Australsk spiller fodbold','https://en.wikipedia.org/wiki/Australian_rules_football','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bilsport','https://en.wikipedia.org/wiki/Auto_racing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Beach Volleyball','https://en.wikipedia.org/wiki/Beach_volleyball','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Breakdancing','https://en.wikipedia.org/wiki/Breakdancing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Klatring','https://en.wikipedia.org/wiki/Climbing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Cricket','https://en.wikipedia.org/wiki/Cricket','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Croquet','https://en.wikipedia.org/wiki/Croquet','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Disc golf','https://en.wikipedia.org/wiki/Disc_golf','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hundesport','https://en.wikipedia.org/wiki/Dog_sport','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Udstillingsøvelse','https://en.wikipedia.org/wiki/Exhibition_drill','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Field hockey','https://en.wikipedia.org/wiki/Field_hockey','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kunstskøjteløb','https://en.wikipedia.org/wiki/Figure_skating','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fodtaske','https://en.wikipedia.org/wiki/Footbag','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Frisbee','https://en.wikipedia.org/wiki/Frisbee','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Golf','https://en.wikipedia.org/wiki/Golf','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hestesko','https://en.wikipedia.org/wiki/Horseshoes','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Isbåd','https://en.wikipedia.org/wiki/Iceboat','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Jukskei','https://en.wikipedia.org/wiki/Jukskei','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kart racing','https://en.wikipedia.org/wiki/Kart_racing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Knivkastning','https://en.wikipedia.org/wiki/Knife_throwing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Langdistanceløb','https://en.wikipedia.org/wiki/Long-distance_running','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Marcherende band','https://en.wikipedia.org/wiki/Marching_band','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Modelfly','https://en.wikipedia.org/wiki/Model_aircraft','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Pickleball','https://en.wikipedia.org/wiki/Pickleball','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Quidditch (sport)','https://en.wikipedia.org/wiki/Quidditch_(sport)','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Race gåtur','https://en.wikipedia.org/wiki/Race_walking','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Racquetball','https://en.wikipedia.org/wiki/Racquetball','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Radiostyret bil','https://en.wikipedia.org/wiki/Radio-controlled_car','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Roller derby','https://en.wikipedia.org/wiki/Roller_derby','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Rugby liga','https://en.wikipedia.org/wiki/Rugby_league','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Roning','https://en.wikipedia.org/wiki/Rowing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Skydesport','https://en.wikipedia.org/wiki/Shooting_sport','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Slædehundevæddeløb','https://en.wikipedia.org/wiki/Sled_dog_racing','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Softball','https://en.wikipedia.org/wiki/Softball','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hurtigløb på skøjter','https://en.wikipedia.org/wiki/Speed_skating','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Squash (sport)','https://en.wikipedia.org/wiki/Squash_(sport)','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tennispolo','https://en.wikipedia.org/wiki/Tennis_polo','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Fastgør bil','https://en.wikipedia.org/wiki/Tether_car','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Tour skøjteløb','https://en.wikipedia.org/wiki/Tour_skating','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Trapshooting','https://en.wikipedia.org/wiki/Trapshooting','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Triatlon','https://en.wikipedia.org/wiki/Triathlon','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Ultimate (sport)','https://en.wikipedia.org/wiki/Ultimate_(sport)','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Vandpolo','https://en.wikipedia.org/wiki/Water_polo','CONCERT','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Læring','https://en.wikipedia.org/wiki/Learning','OBSERVATION','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Meditation','https://en.wikipedia.org/wiki/Meditation','OBSERVATION','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Mikroskopi','https://en.wikipedia.org/wiki/Microscopy','OBSERVATION','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Forskning','https://en.wikipedia.org/wiki/Research','OBSERVATION','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Kortbølgelytning','https://en.wikipedia.org/wiki/Shortwave_listening','OBSERVATION','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Audiofil','https://en.wikipedia.org/wiki/Audiophile','OBSERVATION','INDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Flyspotting','https://en.wikipedia.org/wiki/Aircraft_spotting','OBSERVATION','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Amatør astronomi','https://en.wikipedia.org/wiki/Amateur_astronomy','OBSERVATION','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Bus spotting','https://en.wikipedia.org/wiki/Bus_spotting','OBSERVATION','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Gongoozler','https://en.wikipedia.org/wiki/Gongoozler','OBSERVATION','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Satellitovervågning','https://en.wikipedia.org/wiki/Satellite_watching','OBSERVATION','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Trainspotting (hobby)','https://en.wikipedia.org/wiki/Trainspotting_(hobby)','OBSERVATION','OUTDOOR');
INSERT INTO hobby (name,wiki_link,category,type)  VALUES ('Hvalsafari','https://en.wikipedia.org/wiki/Whale_watching','OBSERVATION','OUTDOOR');